import { Preview, setCustomElementsManifest } from "@storybook/web-components";
import { themes } from "@storybook/theming";
/**
 * Design system
 */
import "@ov-site/style/reset.css";
import "@ov-site/style/styles.css";
/**
 * Storybook dark mode mdx
 */
import "./storybook-dark-mode.css";

/**
 * custom-elements.json contains component metadata and is generated by the "analyze" script.
 */
import customElements from "../custom-elements.json";
setCustomElementsManifest(customElements);

const preview: Preview = {
  parameters: {
    actions: { argTypesRegex: "^on[A-Z].*" },
    controls: {
      matchers: {
        color: /(background|color)$/i,
        date: /Date$/i,
      },
    },
    darkMode: {
      dark: { ...themes.dark, appPreviewBg: "#1d1d1d" },
      light: { ...themes.normal },
      classTarget: "html",
      stylePreview: true,
    },
  },
};

export default preview;
